version: '3'
services:
  # nginx:
  #   build:
  #     context: srcs/requirments/nginx
  #   image: nginx
  #   init: true 
  #   container_name: nginx
  #   ports:
  #     - "443:443"
  mariadb:
    build:
      context: srcs/requirments/mariadb
    image: mariadb
    init: true
    container_name: mariadb
    env_file:
      - .env
    ports:
      - "3306:3306"