version: '3'
services:
  # nginx:
  #   build:
  #     context: srcs/requirments/nginx
  #   image: nginx
  #   init: true 
  #   container_name: nginx
  #   ports:
  #     - "443:443"
  mariadb:
    build:
      context: srcs/requirments/mariadb
    image: mariadb
    init: true
    container_name: mariadb
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - word_press_network
volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/login/data/mariadb_data
      o: bind
networks:
  word_press_network: