version: '3'

services:
  nginx:
    build:
      context: requirments/nginx
    image: nginx
    init: true 
    container_name: nginx
    ports:
      - "443:443"
  mariadb:
    build:
      context: mariadb
    image: mariadb
    init: true
    container_name: mariadb
    args:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"